name: Build API Specification

on:
  workflow_dispatch:

jobs:
  build-api-spec:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3
        with:
          path: sdkjs

      - name: Checkout build_tools repository
        uses: actions/checkout@v3
        with:
          repository: ONLYOFFICE/build_tools
          ref: release/v8.2.0
          path: build_tools

      - name: Checkout sdkjs-forms repository
        uses: actions/checkout@v3
        with:
          repository: ONLYOFFICE/sdkjs-forms
          ref: main  # Specify the branch or tag you want to check out
          path: sdkjs-forms

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Node.js dependencies
        run: |
          cd build_tools/scripts/sdkjs_common/jsdoc
          npm install

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Run Python script to generate docs
        run: |
          cd build_tools/scripts/sdkjs_common/jsdoc
          python generate_docs_md.py
